FROM docker.io/parity/base-bin:latest

COPY target/release/entangle-node /usr/local/bin/entangle-node

USER root
RUN useradd -m -u 1001 -U -s /bin/sh -d /polkadot polkadot && \
    mkdir -p /data /polkadot/.local/share && \
    chown -R polkadot:polkadot /data && \
    ln -s /data /polkadot/.local/share/polkadot && \
    /usr/local/bin/entangle-node --version

USER polkadot

EXPOSE 30333 9933 9944 9615
VOLUME ["/data"]

ENTRYPOINT ["/usr/local/bin/entangle-node"]
