
//! Autogenerated weights for `pallet_pqc`
//!
//! TODO: substituir por weights de benchmark na Fase 5.

use frame_support::weights::Weight;

pub trait WeightInfo {
	fn register_keys() -> Weight;
	fn verify_signature(message_len: u32) -> Weight;
	fn establish_session() -> Weight;
	fn remove_keys() -> Weight;
	fn register_validator_keys() -> Weight;
}

pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);
impl<T> WeightInfo for SubstrateWeight<T> {
	fn register_keys() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}
	fn verify_signature(message_len: u32) -> Weight {
		// ML-DSA verify é computacionalmente pesado (~3ms em CPU moderna).
		Weight::from_parts(100_000_000 + message_len as u64 * 1_000, 0)
	}
	fn establish_session() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
	fn remove_keys() -> Weight {
		Weight::from_parts(20_000_000, 0)
	}
	fn register_validator_keys() -> Weight {
		Weight::from_parts(55_000_000, 0)
	}
}

impl WeightInfo for () {
	fn register_keys() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}
	fn verify_signature(message_len: u32) -> Weight {
		Weight::from_parts(100_000_000 + message_len as u64 * 1_000, 0)
	}
	fn establish_session() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
	fn remove_keys() -> Weight {
		Weight::from_parts(20_000_000, 0)
	}
	fn register_validator_keys() -> Weight {
		Weight::from_parts(55_000_000, 0)
	}
}
